### ISSUE TITLE
好像弹幕处理开关无效

### ISSUE THREAD

**Issue by yy037** [Moraxyc/Bililiveauto#11]
好像弹幕处理开关无效，设置为false后
`0|bililive | Error: 2023-08-11 12:55:54,163 - WARNING - Failed to detect a Telegram user; try sending your bot a message first.
0|bililive | 2023-08-11 12:55:54,163 - WARNING - There were not Telegram chat_ids to notify.
0|bililive | 
0|bililive |     at ChildProcess.<anonymous> (/root/Bililiveauto/apprise.js:36:24)
0|bililive |     at ChildProcess.emit (node:events:514:28)
0|bililive |     at maybeClose (node:internal/child_process:1091:16)
0|bililive |     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
0|bililive | Error: 2023-08-11 13:39:36,791 - WARNING - Failed to detect a Telegram user; try sending your bot a message first.
0|bililive | 2023-08-11 13:39:36,791 - WARNING - There were not Telegram chat_ids to notify.
0|bililive | 
0|bililive |     at ChildProcess.<anonymous> (/root/Bililiveauto/apprise.js:36:24)
0|bililive |     at ChildProcess.emit (node:events:514:28)
0|bililive |     at maybeClose (node:internal/child_process:1091:16)
0|bililive |     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
0|bililive | 转换弹幕格式失败，错误代码: 126

/root/.pm2/logs/bililiveauto-out.log last 15 lines:
0|bililive | 上传 mkv 成功
0|bililive | Send msg Successfully
0|bililive | BiliLiveAuto脚本正在运行, 地址为 http://:::8081
0|bililive | Webhook: 录播姬 POST 到达 事件：SessionStarted
0|bililive | Webhook: 录播姬 POST 到达 事件：FileOpening
0|bililive | Webhook: 判断类型: FileOpening => 提醒未发送
0|bililive | Send msg Successfully
0|bililive | Webhook: 录播姬 POST 到达 事件：SessionEnded
0|bililive | Webhook: 判断类型: SessionEnded => 提醒未发送
0|bililive | Webhook: 录播姬 POST 到达 事件：FileClosed
0|bililive | 弹幕数量：396
0|bililive | 转换弹幕格式失败，错误代码: 126
0|bililive | 转换video格式成功
0|bililive | 上传 mkv 成功
0|bililive | Send msg Successfully`

**Comment by yy037** [comment]
依旧会进行弹幕处理并且报错。而且不会上传弹幕文件

**Comment by Moraxyc** [comment]
那就稍等下吧，我测试后再commit

**Comment by Moraxyc** [comment]
@yy037 可以了，拉最新版的main试试

**Comment by yy037** [comment]
好像还是有点问题？
![截图_20230812110401](https://github.com/Moraxyc/Bililiveauto/assets/89193914/04ff9ff5-a37a-44b2-8a46-c048c11be780)

**Comment by Moraxyc** [comment]
是否确定拉的是最新main分支？PROCESS_DANMU这个环境变量为false?
processFile内是判定这个值为false则直接解决promise并返回，不可能出现日志输出

如果确实是这样配置的还是出错，那就暂时不用管，我过段时间会重构项目为python
